### ISSUE TITLE
hashcode and equals on OWLOntology differ

### ISSUE THREAD

**Issue by mrnolte** [owlcs/owlapi#694] opened 2017-08-15 23:14 UTC
Hey there,
I recently loaded an `OWLOntology` and, after a lot of debugging, checked its `importClosure()`. Two of the imports returned `true`, when invoking `.equals()`, but their `.hashcodes()` were not equal. According to the Javadoc of the two methods, this behaviour is prohibited. The used OWL API version is 5.1.1.. This is my code:
```
final OWLOntologyManager manager = OWLManager.createConcurrentOWLOntologyManager();
final OWLOntology ontology = manager.loadOntologyFromOntologyDocument(new File("original//dc.dublin-core.3.orig"));
ontology.importsClosure().forEach(next -> {
	ontology.importsClosure().forEach(oth -> {
		System.out.println("hashs: " + next.hashCode() + " " + oth.hashCode());
		System.out.println("equals: " + oth.equals(next));
		System.out.println("differ: " + (oth.equals(next) && next.hashCode() != oth.hashCode() || !oth.equals(next) && next.hashCode() == oth.hashCode()));
	});
});
```
The Ontology i loaded can be found as an OWL XML in the original.zip of the BioPortal-Snapshot from [here](https://zenodo.org/record/439510#.WZN9AulCSUl) or, as a single file, here: [dc.dublin-core.3.zip](https://github.com/owlcs/owlapi/files/1226670/dc.dublin-core.3.zip).

Thanks for reading,

Robin Nolte

**Comment by ignazio1977** [comment] 2017-08-16 06:29
`equals()` and `hashCode()` for `OWLOntology` delegate to `OWLOntologyID`

`OWLOntologyID::hashCode()` takes into account both ontology IRI and version IRI, while `equals()` shortcuts on ontology IRI - if it equals the other side, the version IRI is not checked. Possibly this is where the problem arises: two ontologies with the same IRI but different versions are equal but their hashcode might differ.

**Comment by mrnolte** [comment] 2017-08-16 09:06
Thanks for your fast reply.
I hope that this behaviour will be fixed in a future release, since it violates the [Java specification](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--) and causes a lot of problems, for example:
Consider a graph implementation, mapping connected vertexes using a `Hashtable`. This works perfectly fine, but when trying to remove loops in the graph, you can't check for the `hashcode `and must use equals. Since the connected `OWLOntology `are wrongly equals, not only the loops, but also the edges between them would be (in this case wrongly) removed.

**Comment by ignazio1977** [comment] 2017-08-16 16:52
I think it's the hashCode method that's wrong in this case, as - within the same ontology manager - two different versions shouldn't be loaded. So hashCode is using data that it should not rely on.

This will be fixed soon.

**Comment by ignazio1977** [comment] 2017-08-25 14:33
My original analysis was mistaken. The problem is not in OWLOntologyID, it is in the fact that the hashcode value is computed at ontology construction but does not take into account the fact that the ontology id can be changed (for mutable ontologies). This happens often - it happens in your test case, for example. In this case, setting the ontology id should force a recomputation of the hashcode value.

OWLOntologyManager already knew this - to the extent that recomputing the hashcode does not break its ontology retrieval methods.

For your code, it should be sufficient (once the fix is released) to ensure your application does not change ontology ids; if that happens, you need to remove the ontology from the sets/maps containing it and add it again after the id has been changed, to avoid the ontology disappearing in the hash searches.

The fix will be included in the next 5.x release; I'll try to get one done before the end of August.

**Closed** 2017-09-02 07:10 UTC
