### ISSUE TITLE
OWLOntologyMerger fails with ConcurrentModificationException

### ISSUE THREAD

**Issue by ponnou** [owlcs/owlapi#673] opened 2017-06-12 19:30 UTC
Hello all,

I have two ontologies time.ttl and saref.ttl from [Saref](http://ontology.tno.nl/saref/)
saref -> imports time.

So I wanted to merge these two files, I am using the OWLOntologyMerger to load and save the ontologies from a directory. 

Here is the merging part : 

`OWLOntology merged = merger.createMergedOntology(owlManager, mergedOntologyIRI);`

 I have the following error:

Exception in thread "main" java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.semanticweb.owlapi.util.OWLOntologyMerger.createMergedOntology(OWLOntologyMerger.java:86)
	at semanticstore.ontology.library.generator.OntWalker.main(OntWalker.java:82)

**Comment by ignazio1977** [comment] 2017-09-12 20:29
This must be caused by using the same manager to initialise the merger object and in the `createMergedOntology` method; this causes the ontology receiving the merged axioms to also be iterated on to add axioms to itself.

**Closed** 2017-09-15 18:01 UTC

**Comment by charbull** [comment] 2018-01-31 19:07
Hello @ignazio1977 can you please provide us with an example for the OWLOntologyMerger?

Thank you,

**Comment by ignazio1977** [comment] 2018-02-06 07:36
This guarantees the ontology managers are distinct

    OWLOntologyMerger merger=new OWLOntologyMerger(OWLManager.createOWLOntologyManager());
    OWLOntologyManager owlManager=OWLManager.createOWLOntologyManager();
    IRI mergedOntologyIRI=IRI.create("something");
    OWLOntology merged = merger.createMergedOntology(owlManager, mergedOntologyIRI);

**Comment by charbull** [comment] 2018-02-06 22:03
@ignazio1977 great thank you for the clarification

I was wondering about the versioning, how would the merger handles the versioning since now it will merge two or more ontologies each having its own version.
Any recommendation or advice?

thank you for your help,
Charbel

**Comment by ignazio1977** [comment] 2018-02-06 22:10
The OWLOntologyMerger does not handle ontology versions or ontology IRIs, it only merges the axioms themselves - as it says in its javadoc

> A very very simple merger, which just creates an ontology which contains the union of axioms from a set of ontologies.

Ontology annotations, imports, and versions, must be handled separately.

In Java 8, it's actually easier to not use a merger at all. Just take a stream of ontologies, flatmap with `OWLOntology::axioms`, and add the resulting stream to a new ontology.

Which IRI and which version to use are very application dependent choices - I'm not sure what would be a good general strategy.

**Comment by charbull** [comment] 2018-02-06 22:17
Thank you @ignazio1977  make complete sense !
The version should be left to the user/application to decide.

Thank you
