### ISSUE TITLE
owlapi parsers should be vetted for leaking console output

### ISSUE THREAD

**Issue by cmungall** [owlcs/owlapi#550] opened 2016-08-06 18:26 UTC
Whenever we parse an .obo format file we get an error message on the console:

```
[Fatal Error] :1:1: Content is not allowed in prolog.
```

This is in fact not a obo format error message. The message is coming from a org.xml.sax.SAXParseException that naughtily writes to stderr as well as throwing an exception. the exception is caught and the next parser is tried, but the console output has already leaked.

If an upstream fix can't be made then perhaps the OWLAPI could use some heuristics to choose a more optimal order in which to cycle through it's now rather large list of default registered parsers.

**Comment by sesuncedu** [comment] 2016-08-06 19:46
+1

This has sat too long for any good ignoring it has done lately.

I think I started chasing this, and got as far as the realization that
there needed to be an errorHandler set, with no easy place to do it quite
the right way.

It should be easy enough to do better than stderr.

**Comment by ignazio1977** [comment] 2016-08-06 20:10
Files with the .obo extension are a pretty obvious clue to skip XML parsers.

We could also check the first character to skip any XML based parsing, since all sax parsing will fail if the first character is not the start of an XML element (I believe, need to verify that).

**Comment by ansell** [comment] 2016-08-07 22:40
That particular message may be coming from the Rio RDF/XML (SAX) parser, and I am not sure myself how to stop it as I recall looking into it in the past but couldn't find a solution.

**Comment by ansell** [comment] 2016-08-08 00:58
What version of OWLAPI and Sesame are you using? It is possible this was fixed in Sesame after the version that your OWLAPI version is bundling as I can't replicate it with a regression test on the RDF4J codebase that is derived from Sesame-4.1.2.  In RDF4J-2.0M3, there is an ErrorHandler setup to pipe the SAX fatal errors through to the RDF4J ParseErrorListener and an RDFParseException is thrown, but System.err and System.out are not written to anymore.

**Comment by ansell** [comment] 2016-08-08 01:11
This was apparently fixed (by me) in Sesame-2.7.0 so it is strange that it should be appearing again here unless there is another SAXParser in the OWLAPI stack.

Fix references for Sesame are:

https://openrdf.atlassian.net/browse/SES-666

https://bitbucket.org/openrdf/sesame/commits/c1a0bdbc2cc7ae645581b054444bb3f5ab61a55b

**Comment by ignazio1977** [comment] 2016-08-08 08:01
Nice one Peter.
That's a good fix for unnecessary messages, but the parser prioritisation might have performance advantages as well, so we should probably include both.

**Comment by sesuncedu** [comment] 2016-08-09 21:24
The error seems to be generated by the sesame TRIX parser, but not the RDF/XML parser. It is seems to be present in 2.8.x

**Comment by ansell** [comment] 2016-08-09 22:53
Ahh, okay, will look into the TriX parser this time.

**Comment by ansell** [comment] 2016-08-10 02:37
Have opened a pull request fixing the RDF4J TriX parser by attaching an ErrorHandler to the relevant XMLReader, with a regression test for it:

https://github.com/eclipse/rdf4j/pull/282

**Comment by sesuncedu** [comment] 2016-08-10 21:55
Just to double check: will this fix ever be back ported to some version of sesame 2.x?  If not, is it easy to set an error listener from the owlapi trix wrapper?

**Comment by ignazio1977** [comment] 2016-08-10 22:24
Worst case scenario we can add some wrapper classes.

**Comment by ansell** [comment] 2016-08-10 22:49
No, there are not going to be any more Sesame releases as far as I know.

Easiest way to avoid may be to drop TriX from the default set or make sure it is as far back in the heirarchy as possible (hopefully after RDF/XML if that is possible), as RDF/XML should already be okay in 2.7 and virtually noone will use TriX unless they know they want to use it based on my experience.

**Comment by sesuncedu** [comment] 2016-08-10 23:08
An error-listener for trix can be installed by creating a  clone of  RioParserImpl, overriding and cloning the parseDocumentSource, and calling setParseErrorListener.  I tried using a ParseErrorLogger, but this seems to be the wrong thing to do in this case; throwing an exception for fatal errors, without logging, seems to be what is required. 
This seems wrong somehow.

**Comment by ansell** [comment] 2016-08-10 23:33
The issue is that without an ErrorHandler actually in place on the underlying SAX parser, the message always goes to the console just before the exception is thrown. 

If you really wanted to hack it in the most nasty way you could change out System.out and System.err (can't remember which one it actually is right now) just before using the TriX parser, then put them back in place again afterwards, as I did for the unit regression test for RDF4J. In the regression test case the fix is in place so it doesn't actually hide any information, but for OWLAPI you would be doing it to actually hide information which may have side effects for other uses of those channels by other threads/etc.

**Comment by ansell** [comment] 2016-08-10 23:39
ParseErrorCollector may be what you are looking for rather than ParseErrorLogger in the programmatic case, but that still won't help with the underlying SAX exception. Personally, I would either drop the TriX parser from the default set, as I haven't ever actually seen a TriX document in the wild, or take the risky route and do the switcheroo with System.out.

**Comment by sesuncedu** [comment] 2016-08-11 00:06
I so wanted to just drop TRIX, but I kind of got obsessed. 

The "fix" is to create a clone the sesame trix parser, changing the parse(Object) method to create a specially cloned SimpleSaxParser, which has a ~two line change, setting the error handler to be the same default handler as the content handler. 

Also, changing the trix parser factory to create a special Trix RioParserImpl that uses the modified trix parser factory instead of using the Rio Registry, because if a thing isn't worth doing it's worth not doing properly. 

I also have never seen a TRIX document in the wild.

**Comment by ansell** [comment] 2016-08-11 00:36
For reference, if you go down the rabbit hole, feel free to pick up my other similar changes (including substitutable XMLReader implementation that RDF/XML already had) that I did for RDF4J yesterday:

https://github.com/eclipse/rdf4j/commit/70fde6f5fd39bede881e8a2db0215c7d777f6d20#diff-948c36092a90f4b6d3ef037c5771c316L101

**Comment by sesuncedu** [comment] 2016-08-11 00:41
Silly rabbit hole - trix are for kids. 

Pull Request in  #553 -  Not sure if putting a link to the old bitbucket repo is good enough for license purposes.

**Closed** 2016-09-08 21:13 UTC
