### ISSUE TITLE
Detect clashes in ontology imports closure

### ISSUE THREAD

**Issue by hoganwr** [owlcs/owlapi#420] opened 2015-07-01 18:52 UTC
If you import:

http://purl.obolibrary.org/obo/omrse.owl
http://purl.obolibrary.org/obo/apollo_sv/dev/apollo_sv.owl
http://purl.obolibrary.org/obo/omrse/dao.owl

You get an error (see below).

But if you import them in this order, you get no error.  I have two OWL files that illustrate the problem, but obviously cannot attach them here.

http://purl.obolibrary.org/obo/apollo_sv/dev/apollo_sv.owl
http://purl.obolibrary.org/obo/omrse.owl
http://purl.obolibrary.org/obo/omrse/dao.owl

In both cases, the ontology with IRI http://ifomis.org/bfo/1.1 is being loaded multiple times from the URL http://ifomis.org/bfo/1.1.  So why would it error out in one direction and not the other?

The problem then is that Protege always wants to save the file with http://purl.obolibrary.org/omrse.owl in the first position instead of last.

java.lang.RuntimeException: java.lang.RuntimeException: org.semanticweb.owlapi.model.OWLOntologyRenameException: Could not rename ontology. An ontology with this ID already exists: OntologyID(OntologyIRI(http://www.ifomis.org/bfo/1.1))

**Comment by ignazio1977** [comment] 2015-07-01 18:57
This sounds similar to other issues that have been fixed in the OWLAPI. Which version of Protege is this?

**Comment by hoganwr** [comment] 2015-07-01 19:23
beta 17

**Comment by ignazio1977** [comment] 2015-08-08 07:34
I am trying to replicate this but http://purl.obolibrary.org/obo/apollo/dev/apollo_sv.owl is currently not available. If you have access to it, can you post its imports section?

**Comment by hoganwr** [comment] 2015-08-09 01:42
You have the wrong PURL.  It's
http://purl.obolibrary.org/obo/apollo_sv/dev/apollo_sv.owl

Bill

**Comment by ignazio1977** [comment] 2015-08-09 11:10
On 4.1.0 (RC) this issue shows up differently: the problem is that in one order the obsolete.owl ontology is pulled in before geo.owl, and in the other it is pulled in after.
This might be a genuine conflict of imports, but it should not be order dependent.
I'll try with 3.4 and 3.5 to see if there are differences - Protege beta 17 still uses 3.4, if I remember correctly.

**Comment by ignazio1977** [comment] 2015-08-09 11:33
For replication:

    <?xml version="1.0"?>
    <!DOCTYPE rdf:RDF [
    <!ENTITY owl "http://www.w3.org/2002/07/owl#" >
    <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#" >
    <!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#" >
    <!ENTITY rdf "http://www.w3.org/1999/02/22-rdf-syntax-ns#" >
    ]>
    <rdf:RDF xmlns="http://test.org/compleximports/C.owl#"
     xml:base="http://test.org/compleximports/C.owl"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <owl:Ontology rdf:about="http://test.org/compleximports/wrongorder.owl">
    <owl:imports rdf:resource="http://purl.obolibrary.org/obo/iao/dev/obsolete.owl"/>
    <owl:imports rdf:resource="http://purl.obolibrary.org/obo/geo/dev/geo.owl"/>
    </owl:Ontology>
        <owl:Class rdf:about="CClass"/>
    </rdf:RDF>

    <?xml version="1.0"?>
    <!DOCTYPE rdf:RDF [
    <!ENTITY owl "http://www.w3.org/2002/07/owl#" >
    <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#" >
    <!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#" >
    <!ENTITY rdf "http://www.w3.org/1999/02/22-rdf-syntax-ns#" >
    ]>
    <rdf:RDF xmlns="http://test.org/compleximports/C.owl#"
     xml:base="http://test.org/compleximports/C.owl"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <owl:Ontology rdf:about="http://test.org/compleximports/rigthorder.owl">
    <owl:imports rdf:resource="http://purl.obolibrary.org/obo/geo/dev/geo.owl"/>
    <owl:imports rdf:resource="http://purl.obolibrary.org/obo/iao/dev/obsolete.owl"/>
    </owl:Ontology>
        <owl:Class rdf:about="CClass"/>
    </rdf:RDF>


And on 4.1.0 test case:

    package org.semanticweb.owlapi.api.test.imports;

    import org.junit.Test;
    import org.semanticweb.owlapi.api.test.baseclasses.TestBase;
    import org.semanticweb.owlapi.io.StringDocumentSource;
    import org.semanticweb.owlapi.model.OWLOntologyCreationException;

    public class VerifyImportOrderTest extends TestBase {

    @Test
    public void shouldLoadImports() throws OWLOntologyCreationException {
        System.out.println("VerifyImportOrderTest.shouldLoadImports()");
        String input = "<?xml version=\"1.0\"?>\n" + "<!DOCTYPE rdf:RDF [\n"
            + "    <!ENTITY owl \"http://www.w3.org/2002/07/owl#\" >\n"
            + "    <!ENTITY xsd \"http://www.w3.org/2001/XMLSchema#\" >\n"
            + "    <!ENTITY rdfs \"http://www.w3.org/2000/01/rdf-schema#\" >\n"
            + "    <!ENTITY rdf \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" >\n" + "]>\n"
            + "<rdf:RDF xmlns=\"http://test.org/compleximports/C.owl#\"\n"
            + "     xml:base=\"http://test.org/compleximports/C.owl\"\n"
            + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
            + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
            + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
            + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
            + "    <owl:Ontology rdf:about=\"http://test.org/compleximports/wrongorder.owl\">\n"
            + "    <owl:imports rdf:resource=\"http://purl.obolibrary.org/obo/iao/dev/obsolete.owl\"/>\n"
            + "    <owl:imports rdf:resource=\"http://purl.obolibrary.org/obo/geo/dev/geo.owl\"/>\n"
            + "    </owl:Ontology>\n" + "        <owl:Class rdf:about=\"CClass\"/>\n" + "</rdf:RDF>";
        m.loadOntologyFromOntologyDocument(new StringDocumentSource(input));
    }

    @Test
    public void shouldLoadImportsFine() throws OWLOntologyCreationException {
        System.out.println("VerifyImportOrderTest.shouldLoadImportsFine()");
        String input = "<?xml version=\"1.0\"?>\n" + "<!DOCTYPE rdf:RDF [\n"
            + "    <!ENTITY owl \"http://www.w3.org/2002/07/owl#\" >\n"
            + "    <!ENTITY xsd \"http://www.w3.org/2001/XMLSchema#\" >\n"
            + "    <!ENTITY rdfs \"http://www.w3.org/2000/01/rdf-schema#\" >\n"
            + "    <!ENTITY rdf \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" >\n" + "]>\n"
            + "<rdf:RDF xmlns=\"http://test.org/compleximports/C.owl#\"\n"
            + "     xml:base=\"http://test.org/compleximports/C.owl\"\n"
            + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
            + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
            + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
            + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
            + "    <owl:Ontology rdf:about=\"http://test.org/compleximports/rigthorder.owl\">\n"
            + "    <owl:imports rdf:resource=\"http://purl.obolibrary.org/obo/geo/dev/geo.owl\"/>\n"
            + "    <owl:imports rdf:resource=\"http://purl.obolibrary.org/obo/iao/dev/obsolete.owl\"/>\n"
            + "    </owl:Ontology>\n" + "        <owl:Class rdf:about=\"CClass\"/>\n" + "</rdf:RDF>";
        m.loadOntologyFromOntologyDocument(new StringDocumentSource(input));
    }
    }

**Comment by ignazio1977** [comment] 2015-08-09 18:29
Protege 17 is shipping with OWLAPI 3.5.1 in its plugins folder but the error I get with 3.5.1 is the same as 4.x. I suspect this is due to Protege actually bundling more than one OWLAPI version.

The problem here is twofold:
- there is a conflict in the import tree: two incompatible versions of ontology-metadata.owl are imported
(a) https://information-artifact-ontology.googlecode.com/svn/releases/2011-08-04/ontology/ontology-metadata.owl
(b) http://purl.obolibrary.org/obo/iao/dev/ontology-metadata.owl
This is an actual problem in the data, as it is possible that the two versions contradict each other. However, this cannot be solved by the OWL API.
(The problem here is that the two ontologies have the same ontology IRI and the same ontology version (which is set to `$Revision$` - since one of them is from an svn release branch, I believe that could be an error, i.e., the file should have been updated with the actual release version. The trunk version also has a few more axioms.)

- the conflict is revealed only if the imports are loaded in a particular order, i.e., if (b) is loaded first. 

This is because, when (a) is loaded, an ontology with the same ontology id as (b) will be added to a manager; when an import for (b) is found, there is a match in the existing ontologies, so the ontology behind (b) is not actually downloaded, and no conflict emerges. When the order is reversed, there is no match for (a) in the already loaded ontologies. (a) is therefore downloaded, and at the point in which (a) needs to be added to the manager, the homonymy is detected. To avoid throwing an error if the same ontology is loaded through multiple IRIs, the OWL API checks if the axioms in the two ontologies are the same. This is where the incompatibility is actually detected.

So, we have an actual issue, but it is when the import resolution completes successfully that we actually end up with incorrect data. The conflict should have been detected in both cases.

Unfortunately just downloading all the ontologies and checking they're compatible instead of relying on the already loaded ontologies is not a feasible fix, as it would require downloading the same ontologies multiple times every time an ontology appears more than once in the imports closure. For large upper ontologies, this approach is very costly in terms of performance, bandwidth and memory footprint.

However, as a separate validation tool, this makes sense - it would allow developers to check that their imports closure is valid on an ad hoc basis. I'm marking this issue as an enhancement to provide such a tool.

**Closed** 2018-08-12 16:50 UTC
Labels: enhancement
